name: 13 - Using Caching
on:
  workflow_dispatch:
    inputs:
      use-cache:
        type: boolean
        default: true
        description: Whether to execute cache step
      node-version:
        type: choice
        description: node version
        options:
          - 18.x
          - 20.x
          - 21.x
        default: 20.x
jobs:
  build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
          working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        with:
          node-version: ${{ inputs.node-version }}
        uses: actions/setup-node@v3
      - name: Download cached dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: 13-caching/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      - name: Testing
        run: npm run test
      - name: Building
        run: npm run build
      - name: Deploying to nonprod
        run: "Deploying to nonprod"
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 13-caching/react-app
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.cache_key}}
    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        with:
          node-version: ${{ inputs.node-version }}
        uses: actions/setup-node@v3
      - name: Calculate cache key
        id: cache-key
        if: ${{inputs.use-cache}}
        run: echo "cache_key=deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}" >> $GITHUB_OUTPUT
      - name: Download cached dependencies
        if: ${{inputs.use-cache}}
        id: cache
        uses: actions/cache@v3
        with:
          path: 13-caching/react-app/node_modules
          key: ${{steps.cache-key.outputs.cache_key}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit
        run: npm ci
  linting:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: 13-caching/react-app
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        with:
          node-version: ${{ inputs.node-version }}
        uses: actions/setup-node@v3
      - name: Download cached dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: 13-caching/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      - name: Testing
        run: npm run test
      - name: Liting
        run: echo "Linting..."