name: 14 - Working with Artifacts
on: 
    workflow_dispatch:
env:
    build-artifact-key: app-${{ github.sha }}
    test-coverage-key: test-coverage-${{ github.sha }}
jobs:
    test-build:
        runs-on: ubuntu-latest
        defaults:
                run:
                    working-directory: 13-caching/react-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              with:
                node-version: 20.x
              uses: actions/setup-node@v3
            - name: Download cached dependencies
              id: cache
              uses: actions/cache@v3
              with:
                path: 13-caching/react-app/node_modules
                key: deps-node-modules-${{ hashFiles('13-caching/react-app/package-lock.json') }}
            - name: Install dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Unit tests
              run: npm run test -- --coverage
            - name: Upload test results
              with:
                name: ${{env.test-coverage-key}}
                path: 13-caching/react-app/coverage
              uses: actions/upload-artifact@v4
            - name: Build code
              run: npm run build
            - name: Upload build files
              with:
                name: ${{env.build-artifact-key}}
                path: 13-caching/react-app/build
              uses: actions/upload-artifact@v4
    deploy:
        runs-on: ubuntu-latest
        needs: test-build
        steps:
            - name: Download build files
              with:
                name: ${{env.build-artifact-key}}
                path: build
              uses: actions/download-artifact@v4
            - name: Show folder structure
              run: ls -R