name: 15 - Working with Matrices
on: workflow_dispatch
jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{ matrix.os }}-${{ matrix.node }}
        strategy:
            matrix:
                node: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    # - macos-latest
                    - windows-latest
                include:
                    - node: 16.x
                      os: ubuntu-latest
                    - node: 21.x
                      os: ubuntu-latest
                      tag: experimental
            fail-fast: false
        steps:
            - name: Setup node
              uses: actions/setup-node@v6.1.0
              with:
                node-version: ${{ matrix.node }}
            - name: Fail if experimental
              if: matrix.tag == 'experimental' # not use ${{}} in variables here
              run: exit 1
            - name: Perform some tests
              run: |
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
                sleep 10
            - name: Upload test results
              run: echo "Uploading test results"
    include-example:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          color: [red, green]
          shape: [circle, square]
          size: [small, large]
          include:
            - color: red
              opacity: 0.75
            - shape: circle
              opacity: 1.00
            - color: red
              shape: triangle
            - opacity: 0.50
            - color: green
              shape: circle
              size: medium
          exclude:
            - color: green
              shape: circle
      name: ${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}
      steps:
        - name: Dummy step
          run: |
            echo "${{ matrix.color }}-${{ matrix.shape }}-${{ matrix.size }}-${{ matrix.opacity }}"