name: 15 - Working with Matrices
on: workflow_dispatch
jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{ matrix.os }}-${{ matrix.node }}
        strategy:
            matrix:
                node: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
                include:
                    - node: 16.x
                      os: ubuntu-latest
                    - node: 21.x
                      os: ubuntu-latest
                      tag: experimental
            fail-fast: false
        steps:
            - name: Setup node
              uses: actions/setup-node@v6.1.0
              with:
                node-version: ${{ matrix.node }}
            - name: Fail if experimental
              if: ${{ matrix.tag }} == 'experimental'
              run: exit 1
            - name: Perform some tests
              run: |
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"
                sleep 10
            - name: Upload test results
              run: echo "Uploading test results"