name: 15 - Working with Matrices
on: workflow_dispatch
jobs:
    backwards-compatibility:
        runs-on: ubuntu-latest
        name: ${{ matrix.os }}-${{ matrix.node }}
        strategy:
            matrix:
                node: [18.x, 20.x, 21.x]
                os:
                    - ubuntu-latest
                    - macos-latest
                    - windows-latest
        steps:
            - name: Setup node
              uses: actions/setup-node@v6.1.0
              with:
                node-version: ${{ matrix.node }}
            - name: Perform some tests
              run: |
                echo "Running tests on OS ${{ matrix.os }} and NodeJS ${{ matrix.node }}"