name: 17 - 1 - Custom Actions - Composite
on:
    workflow_dispatch:
        inputs:
            target-env:
                type: choice
                options: [dev, prod]
run-name: 17 - 1 - Custom Actions - Composite | env - ${{ inputs.target-env }}
env:
    working-directory: 13-caching/react-app
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ${{ env.working-directory }}
        steps:
            - name: Checkout code repository
              uses: actions/checkout@v4
            - name: Setup Node and NPM Dependencies
              uses: ./.github/actions/composite-cache-deps
              with:
                working-dir: ${{ env.working-directory }}
                node-version: 20.x
                target-env: ${{ inputs.target-env }}
            - name: Test
              run: npm run test 
            - name: Build
              run: npm run build