name: 17 - 2 - Custom Actions - JS
on:
    workflow_dispatch:
        inputs:
            base-branch:
                description: The branch used as the base for the depedency update checks
                default: main
                type: string
                required: false
            target-branch:
                type: string
                description: The branch from which the PR is created
                default: update-dependencies
                required: false
            working-directory:
                type: string
                description: The working directory of the project from which check for dependencies
                required: true
            debug:
                type: boolean
                description: Whether the output debug messages to the console.
                required: false
run-name: 17 - 2 - Custom Actions - JS
jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
              with:
                base-branch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.target-branch }}
                working-directory: ${{ inputs.working-directory }}
                gh-token: ${{ secrets.GITHUB_TOKEN }}
                debug: ${{ inputs.debug }}