name: 17 - 3 - Custom Actions - Docker
on:
    workflow_dispatch:
        inputs:
            url:
                type: choice
                options:
                    - 'https://google.com'
                    - 'https://testing.docker.url.fail'
                required: true
            max_trials:
                type: number
                default: 10
                required: false
            delay:
                type: number
                default: 5
                required: false
jobs:
    ping-url:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Ping URL
              uses: ./.github/actions/docker-ping-url
              with:
                url: ${{ inputs.url }}
                max_trials: ${{ inputs.max_trials }}
                delay: ${{ inputs.delay }}
